from __future__ import annotations

from typing import Any, Protocol, Sequence, runtime_checkable

import numpy as np
from numpy.typing import NDArray


@runtime_checkable
class BackendOps(Protocol):
    """Minimal protocol for array operations needed by the sekai framework.

    Implement this to add support for non-numpy backends (torch, jax, etc.).
    """

    def zeros(self, shape: tuple[int, ...], dtype: Any) -> Any: ...
    def ones(self, shape: tuple[int, ...], dtype: Any) -> Any: ...
    def concatenate(self, arrays: Sequence[Any], axis: int = 0) -> Any: ...
    def stack(self, arrays: Sequence[Any], axis: int = 0) -> Any: ...
    def clip(self, x: Any, lo: Any, hi: Any) -> Any: ...
    def astype(self, x: Any, dtype: Any) -> Any: ...
    def random_uniform(self, rng: np.random.Generator, low: Any, high: Any, shape: tuple[int, ...]) -> Any: ...
    def random_integers(self, rng: np.random.Generator, low: int, high: int, size: tuple[int, ...]) -> Any: ...
    def is_array(self, x: Any) -> bool: ...
    def array_equal(self, a: Any, b: Any) -> bool: ...
